---
# tasks file for wisecorp.rancher
#- name: Create a Deployment by reading the definition from a local file
#  community.kubernetes.k8s:
#    state: present
#    src: /cert-manager.crds.yaml
- name: debug service dns name
  debug:
    var: rancher_dns_name
    
- name: Add jetstack chart repo
  community.kubernetes.helm_repository:
    repo_state: present
    name: jetstack
    repo_url: "https://charts.jetstack.io"

- name: Deploy version {{cert_manager_version}} of cert-manager chart inside cert-manager namespace
  community.kubernetes.helm:
    update_repo_cache: yes
    wait: yes
    wait_timeout: "30m"
    create_namespace: yes
    release_state: present
    kubeconfig: "{{k3s_kube_config_path }}"
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    chart_version: "{{ cert_manager_version }}"
    release_values: 
      installCRDs: true


- name: Add rancher-stable chart repo
  community.kubernetes.helm_repository:
    name: rancher-stable
    repo_url: "https://releases.rancher.com/server-charts/stable"


- name: Deploy version {{ rancher_version }} of rancher chart inside cattle-system namespace with values DNS {{ rancher_dns_name }}
  community.kubernetes.helm:
    update_repo_cache: yes
    wait: yes
    wait_timeout: "30m"
    create_namespace: yes
    release_state: present
    kubeconfig: "{{k3s_kube_config_path }}"
    name: rancher
    chart_ref: rancher-stable/rancher
    release_namespace: cattle-system
    chart_version: "{{ rancher_version }}"
    release_values:
      replicas:  "{{ rancher_options.replicas }}"
      letsEncrypt.email: "{{ letsencrypt_email }}"
      tls: "{{ rancher_options.tls }}" 
      ingress.tls.source: "{{ rancher_options.ingress_tls_source }}" 
      hostname: "{{ rancher_dns_name }}"
      certmanager.version: "{{ cert_manager_version }}"
      noProxy: "{{ rancher_options.noProxy }}"